import '@/styles/globals.css'
import Head from 'next/head';
import Script from 'next/script';
import Layout from '../components/Layout';
import { ThemeProvider } from 'next-themes';

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Workwise</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="images/logo5.png" /> */}
      </Head>

      <Layout>
          <ThemeProvider>
            <Component {...pageProps} />
          </ThemeProvider>
      </Layout>
    </>
  );
}

export default MyApp;

